import streamlit as st
from datetime import datetime

def render_dashboard(transcript, metrics, duration, selected_mode, tier, target_question, persona):
    """Renders the Analysis Results column with Phase 4 placeholders and Export tools."""
    
    st.subheader("2. Analysis Results")
    
    # --- CONTEXT DISPLAY ---
    st.info(f"**Target Question:** {target_question}\n\n**Interviewer Persona:** {persona}")
    
    # --- PHASE 4 PLACEHOLDER (STAR METHOD) ---
    st.markdown("### 🌟 AI Coach Evaluation (STAR Framework)")
    st.caption("LLM Evaluation will appear here in Phase 4. Currently gathering acoustic data.")
    
    c1, c2, c3, c4 = st.columns(4)
    c1.success("Situation: Pending")
    c2.success("Task: Pending")
    c3.warning("Action: Pending")
    c4.error("Result: Pending")
    st.divider()

    # --- ACOUSTIC METRICS ---
    st.markdown("### 📊 Fluency & Delivery")
    feedback = metrics["feedback"]
    
    m1, m2, m3, m4, m5 = st.columns(5)
    m1.metric("Tone", metrics["tone_label"], feedback["tone"], delta_color=feedback["tone_status"])
    m2.metric("Speed", f"{metrics['wpm']} WPM", feedback["wpm"], delta_color=feedback["wpm_status"])
    m3.metric("Pauses", f"{metrics['pause_count']}", feedback["pause"], delta_color=feedback["pause_status"])
    m4.metric("Fillers", f"{metrics['filler_count']}", feedback["filler"], delta_color=feedback["filler_status"])
    m5.metric("Blunders", f"{metrics['blunder_count']}", feedback["blunder"], delta_color=feedback["blunder_status"])

    if "density_tip" in feedback:
        st.info(f"💡 **Delivery Tip:** {feedback['density_tip']}")

    # --- TRANSCRIPT ---
    st.markdown("### 📝 Transcript")
    st.write(transcript)

    # --- REPORT GENERATOR (NEW) ---
    st.divider()
    
    # Generate a clean Markdown string for the download file
    report_md = f"""# AI Interview Coach - Session Report
**Date:** {datetime.now().strftime("%Y-%m-%d %H:%M")}
**Mode:** {selected_mode}
**Interviewer Persona:** {persona}

## Target Question
> {target_question}

## Fluency & Delivery Metrics
* **Pace:** {metrics['wpm']} WPM
* **Tone:** {metrics['tone_label']}
* **Pauses (>1.5s):** {metrics['pause_count']}
* **Filler Words:** {metrics['filler_count']}
* **Blunders:** {metrics['blunder_count']}

## Transcript
{transcript}

---
*Report generated by AI-Powered Interview Coaching System (Capstone Project)*
"""
    
    # --- ACTION BUTTONS ---
    col_retry, col_download, col_debug = st.columns([1, 1, 1])
    
    with col_retry:
        if st.button("🔄 Retry", type="primary", use_container_width=True):
            del st.session_state['results']
            st.rerun()
            
    with col_download:
        st.download_button(
            label="📥 Download Report",
            data=report_md,
            file_name=f"Interview_Report_{datetime.now().strftime('%Y%m%d_%H%M')}.md",
            mime="text/markdown",
            use_container_width=True
        )
            
    with col_debug:
        with st.expander("System Stats"):
            st.write(f"**Hardware Tier:** {tier}")
            st.write(f"**Processing Time:** {duration:.2f}s")